### ISSUE TITLE
check request header to identify user is using native app

### ISSUE THREAD

**Issue by cometta** [manifoldjs/ManifoldJS#102]
Any request header that can be used to check whether user is using manifold JS installed on phone(native app) or using browser ?

**Comment by boyofgreen** [comment]
This is something we need to put in the Wiki, I think just providing a list of the user agents for our supported platforms would be quite helpful.

**Comment by cometta** [comment]
What I meant was how to identify whether user is using a browser to view our website or using manifoldjs webview to view our website? Is there a way when manifoldjs webview doing HTTP request, it insert a header into the request so that we can identify it from website server side?
