### ISSUE TITLE
Enable domain whitelist troubleshooting feature 

### ISSUE THREAD

**Issue by f2bo** [manifoldjs/ManifoldJS#103]
Currently, when an app navigates to a URL from a domain that hasn't been whitelisted, it will launch the URL in the browser. Additionally, any non-interactive network requests (images, scripts) to domains that haven't been whitelisted are blocked.

We should consider including a (runtime) troubleshooting mode for apps generated by ManifoldJS that logs all requests rejected by the current whitelist and generates a report that users can take advantage of to update the whitelist (see "mjs_access_whitelist" member in the manifest).

**Comment by nbeni** [comment]
Will be fixed in release v0.1.4 of ManifoldCordova, created an issue in the ManifoldCordova repository to track status (https://github.com/manifoldjs/ManifoldCordova/issues/38)
