### ISSUE TITLE
browser pop up after click google authentication

### ISSUE THREAD

**Issue by cometta** [manifoldjs/ManifoldJS#106]
For a typical Oauth's flow which redirects to another website(google) to authenticate, it seems browser will pop up instead of rendered on web view.  Is there anyway to force through authentication in webview? I already set white list for accounts.google.com but to no avail.

**Comment by boyofgreen** [comment]
Generally there are two reasons why a page will end up outside of the app:
1. urls not included in whitelist
2. link opens with a new window
  Do you know if the app is set the open auth in a new window?  If not, it might be that google is forwarding you on to a different domain that is triggering auth windows outside the app.  Please let us know if your able to trace it down.

**Comment by boyofgreen** [comment]
Hi Cometta, I'm going to close this issue for now, but if you need any more direction or if I missed the mark with the answer, please let me know

**Comment by chizom** [comment]
Hi, just saw this,I had same issue. But with your suggestion it fixed it. But I'm in a fix.  My Oauth doesn't take me back to the app even if both Oauth and my app use the same webview

**Comment by insolite** [comment]
Hi, @chizom, I'm having the same issue. Just wondering if you managed to solve it somehow?
