### ISSUE TITLE
app package seems to fail when numbers are in the URL

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#109]
Trying to  build site 22tracks.com and I got this error:

ERROR: Failed to create the base application. The Cordova project could not be created successfully.
Command failed: C:\WINDOWS\system32\cmd.exe /s /c ""C:\Users\Jeffrey\AppData\Roaming\npm\node_modules\man
dules\cordova\bin\cordova" create cordova com.22tracks.www Www22tracksCom"
App id contains a reserved word, or is not a valid identifier.

One or more errors occurred when generating the application.

I am wondering if the "reserved word" is the numbers.  maybe we need to convert numbers to letters or skip numbers altogether when we build package names.
version 0.3.1

**Comment by f2bo** [comment]
Yes. It seems to be the numbers. Apparently, you can have numbers but the first character of each segment has to be a letter. 

So all the following app ids fail:
- 2om.tracks.www
- com.2racks.www
- com.tracks.2ww

But these are valid:
- c2m.tracks.www
- com.t2acks.www
- com.tracks.w2w

We'll add some sanitization to the function that generates the App IDs.

**Comment by boyofgreen** [comment]
I think that's all we need.  If we have a segment that starts with a number, we can always skip it or replace it was a different character
