### ISSUE TITLE
The results of conversion

### ISSUE THREAD

**Issue by lee071216** [manifoldjs/ManifoldJS#110]
I test some web sites. A few generated apps run well on the phone, and the others are not good. I find that the web sites designed by Responsive web design can work well. And the web sites which do not adapt to mobile devices looks bad. So is this a normal situation?

**Comment by msrodri** [comment]
Yes, your assessment is correct. ManifoldJS does not modify the rendered content in any way. So if the site does not render correctly in your device's browser you will get the same experience in the web apps generated by ManifoldJS.

It is responsibility of the site's web developer to address these issues. Having said this, we realize that  there are scenarios where you have no control over the website. In these cases, the solution typically requires the app to inject CSS and JavaScript in the loaded pages to fix any rendering issues.

**Comment by lee071216** [comment]
Thanks for your exposition. I have an another question. Where the essential static files(such as image, JavaScript, or CSS) of the generated app are stored? I can't find them in the project directory. Every time I open the app, it sends a request to the server for static resource?

**Comment by msrodri** [comment]
The apps generated by ManifoldJS are actually "Hosted Web Apps", i.e. store apps where its content is hosted on the server (this includes images, JavaScript and CSS files). This means that you need Internet connection to run these apps.

Here are some posts describing Hosted Web Apps that you might find useful:
- http://www.thishereweb.com/hosted-web-apps-explained
- http://www.sitepoint.com/build-hosted-web-apps-android-ios-windows-manifold-js

**Comment by boyofgreen** [comment]
Hi Lee071216,
  I'm working on a little post about this same thing.  It's an important point that turning a site into an app doesn't turn a bad site into a good app.  Also, it doesn't make a desktop web app suitable for a mobile screen.  Thanks for checking out Manifoldjs, hope it meets your needs.
