### ISSUE TITLE
Relationship between scope and mjs_access_whitelist

### ISSUE THREAD

**Issue by vjrantal** [manifoldjs/ManifoldJS#114]
Currently, the documentation and the ManifoldJS output treats `scope` and `mjs_access_whitelist` somewhat similarly.

As a documentation example, quotes from https://github.com/manifoldjs/ManifoldCordova/tree/0215d758528d5d6327101fb62ad45bf833686389#url-access-rules:
> [scope] restricts the URLs to which the application can navigate
> [mjs_access_whitelist] indicates whether URLs matching the rule should be navigated to by the application

As an example of the output, if one has following in the manifest:

```
"mjs_access_whitelist": [
  { "url": "http//login.anotherdomain.com/" }
]
```
The Cordova-related `config.xml` output file will have:
```
<access hap-rule="yes" origin="http//login.anotherdomain.com/" />
<allow-navigation hap-rule="yes" href="http//login.anotherdomain.com/" />
```
The Windows 10 -related `package.appxmanifest` file will have:
```
<uap:Rule Type="include" Match="http//login.anotherdomain.com/" />
```

(see https://github.com/manifoldjs/ManifoldJS/issues/114#issuecomment-120303647 why below has strikethroughs)
I am thinking that the following enhancements might be worth considering:
* ~~The `scope` property would be used only as specified at http://www.w3.org/TR/appmanifest/#scope-member.~~
* ~~The `mjs_access_whitelist` would not be used for settings the navigation scope, but to control the cross-origin network access.~~
  * ~~The change compared to current behavior would be that `mjs_access_whitelist` would generate only `access`-elements to `config.xml` and never `Rule`-elements to `package.appxmanifest`.~~
  * ~~The `scope`-property would generate `allow-navigation` and `Rule` -elements (since the W3C specification currently only has a singular scope, only one element should be generated).~~
* The platform-specific quirks should be documented, for example, currently `mjs_access_whitelist` is ignored when targeting firefox or chrome.

Per specification, if `scope` is omitted, the navigation scope should be unbounded, which could be achieved on some platforms, for example, on Cordova-based platforms with something like `<allow-navigation href="*" />`.

If `mjs_access_whitelist` is omitted, a good default might be to align as closely as possible to the security policies modern Web browsers have. The current default behavior on Cordova-based platforms is more restrictive than in browser environments, for example, a page can't refer to a CSS file in a CDN without whitelisting.

**Comment by vjrantal** [comment]
In the longer run, it might be worthwhile to check if `mjs_access_whitelist` could be deprecated in favor of CORS and CSP once all the target runtimes support them.

**Comment by boyofgreen** [comment]
Hi Vjrantal,
 We actually struggle a bit with area as well.  The whole reason we have the whitelist is because scope doesn't take an array, it only takes a single value.  We have done a lot of apps like this, and we quite often find out that web apps tend to require multiple domains to truly function.  Some require authentication for another domain, others integrate third party services like billing that require multiple domains.
  Anyway we're working with the spec team with the feedback we get.  And for now, we have the whitelist to fill that gap.  Thanks for the feedback, please continue to provide

**Comment by marcoscaceres** [comment]
We should probably add `<origin>` to the W3C's Widget spec to better handle CORS. That way, it can be sent as the `Origin` header (e.g., `Origin: app://foo.com`) allowing CORS to work as expected. I'm happy to do that, but I would need support from Microsoft and Adobe/Cordoba to push it along the W3C rec track. 

About multi origin `scope`, I found the same thing... but people objected because it makes a mess of same origin, tls, etc. However, reality might force us to switch eventually.

**Comment by vjrantal** [comment]
> And for now, we have the whitelist to fill that gap

Got it. Now that you clarified that the whitelist is indeed meant to "extend the scope", I added a strikethrough to my original enhancements list, because it doesn't align with the intent.

I also clearly see the need to allow hosted apps to navigate between multiple origins so no question about that.

I still think that this issue I created is valid, because currently, the `mjs_access_whitelist` is used also for other purposes than "extending the scope". For example, the whitelist at http://shiftr.azurewebsites.net/manifest.json has `{ "url": "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" }`, but the reason is not because the app needs to be able to navigate there, but because of cross-origin resource access. This is due to the fact that the default policy in apps generated for Cordova-based runtimes differ from the one that exists in Web browsers.

I think 2 things could be considered separately:
1. Navigation scope(s)
2. Cross-origin resource and network access

If in ManifoldJS, the intent is to have only one property to control both, it would be good to document it that way.

**Comment by vjrantal** [comment]
> About multi origin scope, I found the same thing... but people objected because it makes a mess of same origin, tls, etc. However, reality might force us to switch eventually.

I agree.

Just as a quick thought, it might be that the best solution isn't to allow defining multiple navigation scopes in the same property, because there are use cases where it matters if this app "represents" certain origin versus "depends on" an origin.

The deep linking specification (https://w3c.github.io/manifest/#deep-links) isn't finalized yet, but I think in those kind of use cases, this might be run into. For example, if my hosted app's scope is foo.com I might want that an operating system considers my app as a "handler" for foo.com URLs. My app might depend on bar.com for authentication, but my app is not a "handler" for bar.com URLs.

Since authentication was used as an example, I was also thinking that from user experience point of view, a valid option might be to run the authentication page in a different ("default") context rather than within the calling app to be able to leverage the SSO / "remember me" of the authentication provider. What I mean by this is that at least in Cordova-based runtimes, the cookie / session / other storage is not shared between apps so even if the user is signed into Facebook in their default browser, the user has to sign in within the Cordova-based app. This is if the navigation occurs within that app's context.

**Comment by marcoscaceres** [comment]
> Since authentication was used as an example, I was also thinking that from user experience point of view, a valid option might be to run the authentication page in a different ("default") context rather than within the calling app to be able to leverage the SSO / "remember me" of the authentication provider. What I mean by this is that at least in Cordova-based runtimes, the cookie / session / other storage is not shared between apps so even if the user is signed into Facebook in their default browser, the user has to sign in within the Cordova-based app. This is if the navigation occurs within that app's context.

True. We need a better `window.open()` to handle these cases - and the ability to share cookies with the browser/webview. Then auth cases would work the same as in desktop.

**Comment by boyofgreen** [comment]
@vjrantal in 0.4.3 we reworked the whole whitelist thing.  Removed whitelist, and simply moved it to scope, extended scope (when you need scope to be an array, still think this part is a WIP), then api_access.  Also we changed whitelist on iOS and Android to work more like windows.  let me know what you think.
