### ISSUE TITLE
v0.3.2 fails on Mac OS with default settings

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#115]
MacOS Yosemite, with v 0.3.2, it fails with default settings.  I get error that it can not generate windows app on this platform and then it doesn't build iOS or Android either.  Was this just my system or is this a bug?
  I was under the impression that windows 8 apps generated okay on mac, just not build.

**Comment by f2bo** [comment]
Unfortunately, not any more. The Windows platform seems to be broken again in Cordova 5.1.1 (when running on a Mac).

The problem can be easily reproduced with Cordova alone. In a Terminal window, run:

``` 
cordova create test511
platform add windows
``` 

env: node\r: No such file or directory

**Comment by msrodri** [comment]
The tool has been updated to remove the `windows` platform from the default platforms list in MacOS and Linux
