### ISSUE TITLE
Allow setting credentials

### ISSUE THREAD

**Issue by unsafecode** [manifoldjs/ManifoldJS#121]
I would like to run manifoldjs against a website that requires authentication, and I coudn't find how to pass them.

Is there a way to set custom headers?

**Comment by f2bo** [comment]
Do you need to be able to authenticate when you execute manifoldJS against the site when generating the hosted app or the generated app itself requires authentication?

If it's for the generated app, then you'll need to send more details.

If you're generating the app with ManifoldJS and you need to log in to do this, you can always download the site's W3C manifest with your browser. To determine the manifest's location, go to the site's URL in your browser, log in, and then examine the page's source. The manifest URL is indicated with a &lt;link&gt; element of type _manifest_.

``` HTML
<head>
    ...
    <title>Shiftr</title>
    <link rel="manifest" href="manifest.json">
    ...
</head>
```

Download the manifest and store it locally. If the site does not publish a manifest, you can create one for the site (see the [W3C spec](http://www.w3.org/2008/webapps/manifest/) to see what kind of information you need to put in it.) The only requirement is that the start_url member needs to be a full URL, not a relative path.

When you generate the app, you can tell ManifoldJS to use the local copy of the manifest using the (**-m** | **--manifest**) parameter.

``` 
manifoldjs http://yoursite.url -c [path-to-the-local-manifest-file]\manifest.json
``` 

If the manifest references any icons that are not accessible without authenticating, you will need to download them too. You can then manually copy them to the correct locations in each platform project of the generated app.

**Comment by boyofgreen** [comment]
this would be a good one to add to the wiki too
