### ISSUE TITLE
build fail for andoid when number starts domain

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#133]
I believe the issue is that the manifest's start_url is https://vas.3m.com. Manifold then tells Cordova to create an Android app with App ID = com.3m.vas, which appears to be invalid due to the "3m" part.

**Comment by JudahGabriel** [comment]
Thanks for fixing this, guys! I just did an npm update, got the latest bits, and it works with our *.3m.com URL.

Thanks for the awesomely-quick turn around!
