### ISSUE TITLE
allow for density to be strings not numbers

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#144]
I've seen a few times this same scenario, and manifoldjs should be smart enough to support:
https://www.npmjs.com/static/images/touch-icons/manifest.json
It expects the density to be a number, not a string representing a number.  it should just work

**Comment by marcoscaceres** [comment]
The spec corrects for this also. See algorithm for how to process the density member (i.e., use `Number.parseFloat()`):

https://w3c.github.io/manifest/#density-member
