### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by nojaf** [manifoldjs/ManifoldJS#148]
I've created a windows10 output from my website. It creates App.jsproj, how would I migrate this to a typescript project?

**Comment by boyofgreen** [comment]
Hi Nojaf, the project you create doesn't have any js in it.  You'll see that it's a very thin wrapper that runs all the code from your server, so if you use typescript on your website or webapp, then it will continue to work.
  Does that answer the question or am I missing the ask ?

**Comment by nojaf** [comment]
Ah ok, yes that answers my question. Thanks.
