### ISSUE TITLE
Allow specifying App ID (bundle identifier) as command line parameter instead of generating automatically

### ISSUE THREAD

**Issue by yasin-siddiqui** [manifoldjs/ManifoldJS#149]
I got the "App id contains a reserved word, or is not a valid identifier" error when I tried to run

manifoldjs http://www.rxcare.in -d /Users/yasin/Desktop/YS/rxcare/rxcare_app/android/rxcare_manifoldjs -s rxcareapp -l debug -p android -b

ERROR: Failed to create the base application. The Cordova project could not be created successfully.
Command failed: /bin/sh -c "/usr/local/lib/node_modules/manifoldjs/node_modules/cordova/bin/cordova" create cordova in.rxcare.www rxcareapp
App id contains a reserved word, or is not a valid identifier.

No error when I change the URL to http://www.rxcare.com instead, but of course that's not an option.

Is there any specific reason that the App ID for the cordova create command can't be accepted as a command-line parameter?

Any suggestions?

**Comment by boyofgreen** [comment]
Hi Yasin-siddique, I'm looking into this.  Will report back soon.

**Comment by boyofgreen** [comment]
looks like we have a few bugs that you've uncovered.  First, it seems like we are not using the argument override of the short name to build the cordova package (we should) in projectBuilder.js:
526   var cordovaAppName = utils.sanitizeName(w3cManifestInfo.content.short_name); 
527   packageName = utils.sanitizeName(packageName); 

Second, our sanitize seems like it should filter out the reserved word (not sure if it's the space or the "in") in utils.js.  
  I think we can add it the current iteration so we have it fixed for you ASAP.

**Comment by boyofgreen** [comment]
Hey Yasin,
  Just wanted to let you know the fix is in master now for the issue with .in domains.  Thanks for helping us discover and swash this bug!  We hope you build a lot of apps and get very rich from it.  Unless of course the money would corrupt you, then we'll hope for just moderate success :)

**Comment by yasin-siddiqui** [comment]
Hey Jeff,

Many thanks for letting me know.

Looking forward to pulling the latest version and trying it out again over
the weekend.

Best Wishes,
Yasin
