### ISSUE TITLE
Icon "sizes" argument does not accept a list of sizes

### ISSUE THREAD

**Issue by erkkah** [manifoldjs/ManifoldJS#151]
manifoldjs currently assumes that the "sizes" attribute on icons is a single WxH size. Providing a list of sizes does not work.

**Comment by boyofgreen** [comment]
Hi Erkkah, thanks we'll keep this open as a bug.  We've talked about this, and currently we don't know of any of our platforms that support the .ico file, so in order to support that we would need to add a converter too.  It is in the roadmap.

**Comment by erkkah** [comment]
I believe I have misinterpreted the manifest draft, or how the resulting icon images are used in the different target platforms. My understanding was that the "sizes" attribute is to be used as a hint, and that I could use a list of sizes to use for example a 128x png for several target sizes.

There is nothing limiting me from entering several image objects referring to the same 128x png, but with different sizes, and these will then pass through to the different target platforms unmodified.

**Comment by boyofgreen** [comment]
HI Erkkah,   Yes, the sizes are more than hints, they determine what files are used where.  I think your approach will work, but as we see more browsers impliemnt, then it will probably become clearer :)
