### ISSUE TITLE
theme color seems to be broken

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#157]

**Comment by msrodri** [comment]
It looks like the `theme_color` member of the manifest can be case-insensitive, but the `BackgroundColor` attribute in the Windows 10 manifest should be in lower camel case. If the background color value does not meet this rule in a Windows 10 Hosted Web Apps, it is considered invalid and the app fails during build.

This is the build error reported in Visual Studio when a Windows 10 Hosted Web App is generated using an input manifest with `aliceblue` as `theme_color`:

![image](https://cloud.githubusercontent.com/assets/924201/11383021/236e5538-92e4-11e5-824d-0a30ffe19766.png)

This is the error message shown in the manifest properties:
![image](https://cloud.githubusercontent.com/assets/924201/11382673/f9730730-92e1-11e5-847b-aa4538827561.png)
