### ISSUE TITLE
New Platforms generated from Manifoldjs

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#162]
There have been requests to expand the number of platforms that are generated with Manifoldjs.  This issue will be used to collect info on the requested platforms and research on viability.

**Comment by IntranetFactory** [comment]
I'm currently missing support for major desktop OS - mainly OSX and Linux. So maybe Electron (http://electron.atom.io/) and the Electron Packager (https://github.com/maxogden/electron-packager) can be integrated or extended to understand the same manifests.
