### ISSUE TITLE
Will you support Chrome Custom Tabs?

### ISSUE THREAD

**Issue by erlend-sh** [manifoldjs/ManifoldJS#165]
Does ManifoldJS intend to support [Chrome Custom Tabs](http://blog.chromium.org/2015/09/chrome-custom-tabs-smooth-transition_2.html)? It seems to oftentimes be preferable over WebView.

<img alt="screen shot 2015-10-02 at 22 33 13" src="http://2.bp.blogspot.com/-vEZVspV3wpg/Vecob7noZiI/AAAAAAAAAm8/Iaj912SKWNs/s1600/CCT_Large.gif">

Example code here:

https://github.com/GoogleChrome/custom-tabs-client

**Comment by boyofgreen** [comment]
Yea this looks really cool and well aligned.  We'll look into this for the next version.  Thanks for brining it to our attention, it seems like an experience that a lot of devs might prefer.
