### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by EdSF** [manifoldjs/ManifoldJS#167]
Disclaimer: complete n00b (in fact first time):

Was getting exited after watching all the videos, [this "old" issue on SO](http://stackoverflow.com/questions/30432953/using-manifoldjs-with-windows-10-10122-has-anyone-got-the-app-to-show-up)  is exactly all I can get. Same with the [Getting Started (shiftr app)](https://github.com/manifoldjs/manifoldJS/wiki/Getting-Started) and subsequently running `ManifoldJS run windows`

Am probably (likely) missing something fundamental(?)

Other interesting items:
- Android - seems to require sdk-22 (23 is current)

Is there a way to log runtime errors?  The window that appears above is actually too fast in my case - not 30 seconds (as described in the SO post) - more like a second (or less) so there is no way for me to see what looks like an error message (I'm assuming that's what it is - I have no chance to read it).

Thank you.

**Comment by boyofgreen** [comment]
Welcome to the club!  We're glad that your trying the tool.  A few questions:
1. What platform are you running to tool on (can I assume windows 10)?
2. What is the URL of the site you are building?
  If I had to guess, I would say it could be a certificate issue on your site.  Windows 10 doesn't display anything if it's "mixed" content.  it either has to be http or https.  The other thing it could be is a redirect that is taking you to another domain, which is being blocked.   If you are running the tool on windows 10 with visual studio 2015 installed, you can get inside the created directory and type "manifoldjs visualstudio" and that will pop you into visual studio where you can do some deeper debugging.
  For the android issue, we are currently targeting version 22, which is what our version of Cordova targets, we'll be updating soon, rest assured you can still run it on 23.
Thanks!
jeff

**Comment by EdSF** [comment]
Hi Jeff,

Great stuff - just need to grok more on my part :) So here goes:

- Windows 10 (Pro - if that matters at all)
- VS 2015 (though 12 and 13 are installed too, if this matters at all)

--

I did see the difference after tinkering some more after posting the question and this is what I got:

 1. Running in VS succeeds
  - this is true if I use the command line `manifoldjs visualstudio`
-  or open the `sln` file directly and run it from there (just like any other VS sln)

 2. Running VS via command line (above) opens the `App.jsproj` project in the `[app]/windows10/source` folder. Debugging succeeds

 3. Manually opening the `sln` in `[app]/cordova/platforms/windows` in VS and running/debugging succeeds too - for all (`Win 8.1 Phone`, `Win 8.1`, `Win10(universal)`, `80(8.1)`)
  - _Note_: the Windows 10 `jsproj` being referred to here isn't the same as above

 4. Android - 
  - partially resolved by obtaining sdk-22
  - `manifoldjs run android` will successfully launch the emulator but the app doesn't seem to be "pushed" (doesn't get loaded in emulator). 

---

So it seems its running the app via command line is what fails. An additional question pops up in the Windows 10 projects - one in the `cordova` folder vs. the other in the `windows10/source`). 

The Android issue is probably something I'll have to deal with on the emulator side...

So from a total n00b like me, trying to put things together from start to finish so to speak.

Thank you - keep up the great work!

**Comment by EdSF** [comment]
Closing this. It's just an annoyance at the end of the day. For Android, just follow [the build instructions](http://manifoldjs.com/deploy), and use Android Studio to debug. If you're on Windows/VS, my tip is to use the Visual Studio Emulator for Android (faster).
