### ISSUE TITLE
manifoldjs run windows gives powershell errors

### ISSUE THREAD

**Issue by KvdM** [manifoldjs/ManifoldJS#172]
Installed it on a freshly installed Windows 10 (upgrade from 8.1). I used travelcontose.azurewebsites.net to generate the stuff but when I run manifoldjs run windows I get errors

<img width="437" alt="manifoldjs error" src="https://cloud.githubusercontent.com/assets/1250133/10791980/10db9d5e-7d8b-11e5-80e1-6155101eaec3.png">

I already tried setting powershell to execution policy unrestricted and rebooting but to no succes. Anyone an idea?

**Comment by boyofgreen** [comment]
I wonder if you need to put your computer in dev mode to side load.  Go into settings and search for developer mode, and see if you have it set.
![capture](https://cloud.githubusercontent.com/assets/1182499/10793319/65e57d2e-7d5e-11e5-91f8-103a633d79c8.PNG)

I wouldn't expect this error from that, but it's worth checking first.  I'll reach out to the guy who owns that package (it's a dependency) and see what he think.

**Comment by KvdM** [comment]
Awesome, that did the trick. On my other laptop it directly worked but on that I made a fresh install and opted for developer mode.

**Comment by boyofgreen** [comment]
Great!  I hope the demo goes well, let me know if you need any other support.

**Comment by alxlu** [comment]
Glad to see it's working. In the future if you want to save a step, you don't actually don't need to change the powershell execution policy&mdash;you only need to enable developer mode.
