### ISSUE TITLE
Created images should be used instead of manifold logo

### ISSUE THREAD

**Issue by jonasvanderhaegen** [manifoldjs/ManifoldJS#181]
For example:

http://staging-sessie.jonasvanderhaegen.be/
I created 30 square logos and 13 splash screen with photoshop, mentioned them in my manifest.json. Got no warnings, errors, or suggestions on the manifold generator whatsoever. 

After I manifold the website, not a single one was copied to the Android and Windows platform on my laptop. on ios it's 50/50. 50% my images, 50% manifold logo's.

**Comment by mattwoberts** [comment]
Did you reference the icons in the manifest as relative paths? 

This works for me - the icons are copied over as they should be when I `cordova prepare` - but I'm having issues with them not being used by the app (https://github.com/manifoldjs/ManifoldCordova/issues/57)

**Comment by jonasvanderhaegen** [comment]
@mattwoberts http://staging-sessie.jonasvanderhaegen.be/manifest.json
They're all as relative paths yes. Saw your link and having the same yea, just getting the manifold logo instead of mine ;)

**Comment by f2bo** [comment]
Sorry. We've been busy and haven't had time to investigate further, but it seems that the manifest in your site references JPG images instead of PNGs. Manifo

**Comment by f2bo** [comment]
(Accidentally pressed send before finishing.)

ManifoldJS only copies PNG images. I honestly can't remember why we did it this way, but I suspect that when we started the project, Cordova didn't support JPG images as icons. It seems that currently if you supply a JPG image, Cordova converts it to PNG, so we should remove this restriction in ManifoldJS. 

For the time being, if you convert your images to PNG format, they should work.

**Comment by boyofgreen** [comment]
Hey @jonasvanderhaegen can you confirm it was an issue with the format?  I want to make sure your taken care of.  We'll look at removing the block of the PNGS

**Comment by jonasvanderhaegen** [comment]
@boyofgreen I used a photoshop script to open and save them all as pngs, updated the manifest.json. Not all images are used still, like what I mentioned in my first post. It's not that much of a problem really but I just like to help.

**Comment by boyofgreen** [comment]
yea, we want to support everything that the W3C manifest does, and it would work for them.   I'll work with @f2bo to figure out what needs to change on our end.  I know we can't get it in 0.4.3, but likely 0.4.4

**Comment by jonasvanderhaegen** [comment]
Alright, sweet!
