### ISSUE TITLE
Using deprecated NPM packages

### ISSUE THREAD

**Issue by martinkearn** [manifoldjs/ManifoldJS#190]
When installing ManifoldJS via the command line, you'll get warnings about several deprecated/renamed packages that are in use. 

Not sure if this is actually a problem but I'd prefer not to get warnings when installing things.

npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

**Comment by f2bo** [comment]
Thanks for reporting this. 

None of these are direct dependencies of ManifoldJS. It seems that they are pulled in by another package, **cheerio**. ManifoldJS currently depends on v0.18.0. The current release of cheerio (v0.19.0) has apparently updated its dependencies. We'll need to test it and update to this version to remove the warnings.

**Comment by boyofgreen** [comment]
Martin, just because a dependency has been abandoned doesn't mean it's not safe!  Just a joke.  0.18 was the latest version when we took it on, but now that .19 is out, we'll put it into an update to keep things on the up and up.

**Comment by boyofgreen** [comment]
close this issue, and open one for new packages that are depricated
