### ISSUE TITLE
manifoldjs run windows opens map app?

### ISSUE THREAD

**Issue by MartinT86** [manifoldjs/ManifoldJS#193]
Hi,

I've been trying to get manifoldjs to work for a windows 10 app.

After reading an issue on here that i needed to put windows 10 into developer mode, im past the powershell errors.

However, now when i run manifoldjs run windows, the powershell script runs but then opens up the windows map app.

Can anyone help with this? 

thanks

**Comment by alxlu** [comment]
I'm wondering if it's somehow possible the GUID in the manifest somehow happened to match up with the Map App's appid. Can you open powershell, and run `Get-AppxPackage` and paste the output here?

**Comment by MartinT86** [comment]
Hi,

So i ran Get-AppxPackage *maps*

and the result was

Name              : Microsoft.WindowsMaps
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 4.1511.3161.0
PackageFullName   : Microsoft.WindowsMaps_4.1511.3161.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsMaps_4.1511.3161.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsMaps_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.22929.0_x64__8wekyb3d8bbwe,
                    Microsoft.NET.Native.Framework.1.1_1.0.23115.0_x64__8wekyb3d8bbwe,
                    Microsoft.NET.Native.Runtime.1.1_1.1.23406.0_x64__8wekyb3d8bbwe}

Name              : Microsoft.WindowsMaps
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 4.1505.50619.0
PackageFullName   : Microsoft.WindowsMaps_4.1505.50619.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsMaps_4.1505.50619.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsMaps_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.22929.0_x64__8wekyb3d8bbwe,
                    Microsoft.NET.Native.Framework.1.0_1.0.22929.0_x64__8wekyb3d8bbwe,
                    Microsoft.NET.Native.Runtime.1.0_1.0.22929.0_x64__8wekyb3d8bbwe}


any help is greatly appreciated

**Comment by alxlu** [comment]
Can you post your AppxManifest.xml file?

Also, when you check your apps, is the app you were trying to install installed? Or was it not installing anything and only launching the Maps app?

**Comment by MartinT86** [comment]
Please see below for the manifest.
Actually, you are correct, the app is installing. Sorry, think i've been misunderstanding what was supposed to happen.

Wonder why the install opens maps though?

Thanks

**Comment by alxlu** [comment]
It's also supposed to launch the correct app, so there may still be a bug somewhere. When the package is installed, it should return the package info for the app and then use that to launch the app. See: https://github.com/MicrosoftEdge/hwa/blob/master/AppxUtilities/Start.ps1#L8-L10

It's interesting that it manages to install the correct app, but launches the incorrect one because the package info should be passed directly to the Launch script. If you run it again, do you see two loading bars in the powershell window or just one?

Somehow it's getting confused with the built in maps app. Taking a look at your `AppxManifest.xml` file may provide some clues as to what's going on.

**Comment by alxlu** [comment]
@david-risney, do you know what might be causing `Launch-AppxPackage.ps1` to launch the wrong app if the package info has been directly passed in from `Add-AppxPackageExt.ps1`?

**Comment by david-risney** [comment]
I don't. It would be helpful to see the get-appxpackage results of MartinT86's installed package and their appxmanifest.xml.

**Comment by boyofgreen** [comment]
@MartinT86   What site are you using it against?  We should see if we can recreate the issue on a different machine.  Maybe the site URL is triggering a keyword or something

**Comment by MartinT86** [comment]
Hi,

Thanks for the responses.
I've just tried it against another site SmashingMagazine.com

The maps app started again but the app did install successfully.
get-appxpackage *WwwSmashingmagazineCom* returned nothing?

The app manifest is;

<?xml version="1.0" encoding="UTF-8"?>

-<Package IgnorableNamespaces="uap mp build" xmlns:build="http://schemas.microsoft.com/developer/appx/2015/build" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10">

<Identity ProcessorArchitecture="neutral" Version="1.0.0.0" Publisher="CN=INSERT-YOUR-PACKAGE-IDENTITY-PUBLISHER-HERE" Name="INSERT-YOUR-PACKAGE-IDENTITY-NAME-HERE"/>

<mp:PhoneIdentity PhonePublisherId="00000000-0000-0000-0000-000000000000" PhoneProductId="e187091d-1682-3a5e-ce95-9214756d6b06"/>


-<build:Metadata>

<build:Item Name="ManifoldJSVersion" Value="0.4.3"/>

<build:Item Name="GeneratedFrom" Value="CLI"/>

<build:Item Name="GenerationDate" Value="2015-12-09 19:18:46 Z"/>

</build:Metadata>


-<Properties>

<DisplayName>WwwSmashingmagazineCom</DisplayName>

<PublisherDisplayName>INSERT-YOUR-PACKAGE-PROPERTIES-PUBLISHERDISPLAYNAME-HERE</PublisherDisplayName>

<Logo>images\storelogo.scale-100.png</Logo>

</Properties>


-<Dependencies>

<TargetDeviceFamily Name="Windows.Universal" MaxVersionTested="10.0.10240.0" MinVersion="10.0.10240.0"/>

</Dependencies>


-<Resources>

<Resource Language="en-us"/>

</Resources>


-<Applications>


-<Application StartPage="http://www.smashingmagazine.com/" Id="WwwSmashingmagazineCom">


-<uap:VisualElements BackgroundColor="blue" Description="WwwSmashingmagazineCom" Square44x44Logo="images\smalllogo.scale-100.png" Square150x150Logo="images\logo.scale-100.png" DisplayName="WwwSmashingmagazineCom">

<uap:SplashScreen Image="images\splashscreen.scale-100.png"/>


-<uap:InitialRotationPreference>

<uap:Rotation Preference="portrait"/>

</uap:InitialRotationPreference>

</uap:VisualElements>


-<uap:ApplicationContentUriRules>

<uap:Rule Match="http://www.smashingmagazine.com/" WindowsRuntimeAccess="none" Type="include"/>

</uap:ApplicationContentUriRules>

</Application>

</Applications>


-<Capabilities>

<Capability Name="internetClient"/>

<Capability Name="privateNetworkClientServer"/>

</Capabilities>

</Package>

great talk by the way at stacked in manchester @boyofgreen

**Comment by boyofgreen** [comment]
Hi @MartinT86 
  Thanks for the kind words.  I actually just tried this on my machine and did not get the maps app to open.   

@david-risney  Is it possible that the maps app is cached by the Add-AppxPackage?

**Comment by david-risney** [comment]
Did it work correctly for you?

Add-AppxPackageExt shouldn't be caching anything. I'm not sure exactly which version of the script was copied into this project but it may be that if nothing is actually installed (exact same package already installed) it will attempt to find the already installed package based on the manifest's info and perhaps found the wrong package. Other than that I'm not sure how this would happen.

**Comment by boyofgreen** [comment]
Hi @MartinT86 are you still getting this issue?
