### ISSUE TITLE
manifoldjs.com not generating iOS and Android packages

### ISSUE THREAD

**Issue by hbcondo** [manifoldjs/ManifoldJS#195]
I'm just starting to look at ManifoldJS and tried the online generator. Per the attached screenshot, the manifoldjs.com generator doesn't produce iOS and Android packages. Also, the cordova package's index.html file only renders the default Phonegap content "Hello World". Are these expected behaviors? 

![image](https://cloud.githubusercontent.com/assets/306958/11916010/2bd27f64-a677-11e5-9f16-ba443ce567bb.png)

**Comment by boyofgreen** [comment]
Hey @hbcondo   Thanks for putting the issue in.  I just tried this myself and some some similar behaviors.  My top level folder looked like yours:

![1](https://cloud.githubusercontent.com/assets/1182499/11932707/fd8710e2-a7bc-11e5-998e-f5cb29dee1df.PNG)

but then when I dug into the platforms folder, I saw that it did generate the ios / Android, it just didn't make the shortcuts for them

![2](https://cloud.githubusercontent.com/assets/1182499/11932902/3111e878-a7be-11e5-8b41-5ed0da812c79.PNG)
 
Do you see the files paltforms there by chance?

**Comment by hbcondo** [comment]
Thank you, @boyofgreen. I can confirm these folders do get outputted to my cordova / platforms directory. In each of these platform folders, is it possible to test in a web browser before going through the IDE? The manifoldjs.com/deploy web page mentions this but when I try it, the default Apache Cordova web page is loaded with some clientside errors. I also tried the steps mentioned in issue 156 by setting up a web server and copying www and cordova files. 

Sorry for the newbie questions but I'm hopeful manifoldjs will end up saving me a lot of dev time :)

![image](https://cloud.githubusercontent.com/assets/306958/11939630/3aa6f1ac-a7d8-11e5-8568-7176cc259bbc.png)

**Comment by boyofgreen** [comment]
Right we have some test portal that will help you test everything before hand.  I haven't released the iOS one yet, but hoping to next week:

Windows 10
http://www.microsoft.com/en-us/store/apps/manifoldjs-test-portal/9nblggh5xghj

Android
https://play.google.com/store/apps/details?id=net.azurewebsites.mjsroller

Note, the windows one does allow you to test all the Windows API, but android and iOS don't have a mechanism for adding cordova plugins to the test portal yet.

Hope this helps.
Thanks,
Jeff
