### ISSUE TITLE
On github I read : "Chrome Hosted Apps" in Supported Input Manifests but...

### ISSUE THREAD

**Issue by ArfyFR** [manifoldjs/ManifoldJS#201]
But with a "generic"/example Chrome Hosted app like the one shown here
`https://developer.chrome.com/apps/first_app`
I mean with inside manifest.json
```
{
  "name": "Hello World!",
  "description": "My first Chrome App.",
  "version": "0.1",
  "manifest_version": 2,
  "app": {
    "background": {
      "scripts": ["background.js"]
    }
  },
  "icons": { "16": "calculator-16.png", "128": "calculator-128.png" }
}
```
it seems **not work**.  I get a

> ERROR: Could open the manifest file.

(I am trying _manifoldjs -m <dir_where_manifest_is>_)

There is another option/argument for Chrome Hosted app ?

**Comment by boyofgreen** [comment]
yep so you'll still need to pass in the URL, esiecially since chrome doesn't have it in the above manifest.  So try manifoldjs http://www.mysite.com -m manifest.json

**Comment by ArfyFR** [comment]
Thanks, but...
I tried with my app and got an Error

So I tried with Google "hello world" sample:
https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/hello-world

and same result:
ERROR: Invalid manifest format.

Arfy

**Comment by f2bo** [comment]
I believe the manifest you mention is for a packaged app, not a hosted app and it's missing the launch URL. For example:
```
{
  "name": "Hello World!",
  "description": "My first Chrome App.",
  "version": "0.1",
  "manifest_version": 2,
  "app": {
    "launch": {
       "web_url": "http://yourdomain.com/hello"
    }
  },
  "icons": { "16": "calculator-16.png", "128": "calculator-128.png" }
}
```

**Comment by ArfyFR** [comment]
Hi,
This mean ManifoldJS may only "convert" hosted app ?

**Comment by f2bo** [comment]
Correct. ManifoldJS generates hosted apps.

**Comment by ArfyFR** [comment]
Ok thanks... =)
