### ISSUE TITLE
CSS Injection like WAT

### ISSUE THREAD

**Issue by martinkearn** [manifoldjs/ManifoldJS#203]
The predecessor for ManifoldJS (WAT) used to allow CSS injection such that the app could affect how the site rendered via the app by injecting CSS.

For me this was the number 1 feature of WAT and it is something that I do miss occasionally in ManifoldJS.

This is more like a feature request than issue and there may well be technical reasons why this is not possible in a cross platform way, but I thought I'd pop something in here to at least start the discussion.

**Comment by englishextra** [comment]
all clear - you are a gallant soldier

**Comment by boyofgreen** [comment]
Hey Martin, I've got some good news for you.  We actually added the ability to inject js (which can be a script tag) in the last version, you can see a walk through on this wiki page:https://github.com/manifoldjs/ManifoldJS/wiki/Using%20Cordova%20Plugins%20in%20Hosted%20Web%20Apps#importing-scripts
