### ISSUE TITLE
Guide not working with Android 5.1.1 cordova?

### ISSUE THREAD

**Issue by gabn88** [manifoldjs/ManifoldJS#204]
I followed the guide to the letter, only changed the plugin.xml so that         

    <engine name="cordova-android" version=">=4.1.1" /> instead of lower then (to make it build).

However the example is not working for me. Could it be that cordova-android 5.1.0 is not supported?

**Comment by gabn88** [comment]
it does seem to work now, however I get a Uncaught Error: cordova already defined error now...

**Comment by boyofgreen** [comment]
Hi Gabn88, we usually bump the cordova version every time we release.  Usually it runs fine with all version of cordova, but we've had a few cases where it broke on us, so we capped the cordova version to the ones we've tested with.  We'll be testing for 5.1.0 (or whatever is current) in 0.5.1.  So are you moving forward okay now?  Anythign you need form us?
Thanks,
Jeff

**Comment by gabn88** [comment]
Hi boyofgreen! 

Thanks for the feedback! It seems to work, except some issues with the cordova loading to late on the page (after all js is loaded, or even after all images have loaded (and if one gives a 504, it fails)).
