### ISSUE TITLE
Same problem as issue #172 but suggested solution is not working

### ISSUE THREAD

**Issue by wxb1** [manifoldjs/ManifoldJS#209]
https://github.com/manifoldjs/ManifoldJS/issues/172

I am getting the same problem but setting the developer mode is not working.

**Comment by wxb1** [comment]
![test](https://cloud.githubusercontent.com/assets/19365422/15270414/e9de713a-19e4-11e6-8230-7232324dc944.jpg)

**Comment by wxb1** [comment]
Lovely... The problem was there was a space in the directory name and LaunchAppxPackage.ps1 is looking for  a folder with NO spaces in it. Once I removed the spaces the application launched!

**Comment by boyofgreen** [comment]
thanks for the heads up.  I think we can fix this.
