### ISSUE TITLE
MacOS: Apps generated from Manifoldjs.com/generator fail at packaging for Windows 10.

### ISSUE THREAD

**Issue by AmazingJaze** [manifoldjs/ManifoldJS#218]
The store app generated from Manifoldjs.com/generator will not package, using a Macbook Pro running OS X El Capitan
### Notes
- This does not repro when following the same steps on my windows 10 machine.
- This also does not repro on my MacBook  Pro if I generate the store app using the manifoldjs npm module `manifoldjs https://AmazingJaze.github.io/super-rentals/` to generate the store app, instead of the manifoldjs.com/generator tool

<hr />

### Repro

1. navigate to manifoldjs.com/generator,  
2. enter the url https://AmazingJaze.github.io/super-rentals/ and click [get started]
3. On the next page, click [Generate package] without entering any data other than what was auto filled.
4. After the store app is generated follow the steps listed in the generated readme.md file. 
   <br /> **a.k.a**  Associate the appmanifest.xml inside of the generated Windows10 folder with the 3 fields from your Microsoft Dev Center App identity.
5. From inside the "projects" folder run `manifoldjs package -p windows10`
### Output

``` bash
➜   manifoldjs package -p windows10
[error] manifoldjs  : Failed to package the Windows 10 Platform app.
                      Failed to create the package. The CloudAppX service returned an error - Internal Server Error (500): APPX package generation failed. Error info: /*[local-name()="Package" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"]/*[local-name()="Applications" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/*[local-name()="Application" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/*[local-name()="VisualElements" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/uap/windows10"][1]/*[local-name()="InitialRotationPreference" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/uap/windows10"][1]/*[local-name()="Rotation" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/uap/windows10"][1]/@Preference
                      Package creation failed.
                      0x80080204 - The specified package format is not valid: The package manifest is not valid.
[error] manifoldjs  : One or more platforms could not be generated successfully.
                      For more information, run manifoldjs with the diagnostics level set to debug (e.g. manifoldjs [...] -l debug)
```

**Comment by AmazingJaze** [comment]
Edited above comment to clarify repro steps.

**Comment by AmazingJaze** [comment]
Repro rate is 3/3 for me. I don't suppose Manifoldjs.com/generator is using an older version of ManifoldJS than the latest npm module?

**Comment by boyofgreen** [comment]
Hi Jesse.  Manifoldjs.com doesn't package so I think it's a different issue.   Can you validate that you have updated the name, app ID etc inside the xml manifest?  

@f2bo am I remembering that there might be some periodic cleanup to do in cloudAppx ?

**Comment by AmazingJaze** [comment]
Hi @boyofgreen I think my last comment may have been a little misleading.  I only experience this issue when I use the manifoldjs npm module to package a store app that was generated from the manifoldjs.com/generator site.  

I don't see this error if I use the manifoldjs npm module to package a store app that was also generated by the manifoldjs npm module. 

So I was wondering if this could be caused by the generator at manifoldjs.com being an older version of manifoldjs than what the latest npm module is. Hopefully that adds more context to my previous comment.

**Comment by boyofgreen** [comment]
okay, that makes more sense.  The web generator is behind a few version, and I just realized the message doesn't appear on the site.  I must have not pushed it out alll the way.  The issue we ran into with the web generator is around cordova (not windows 10) as it seems to be taking longer to do builds and the server times out.  However I'm not sure why the build would not work, I'll try it out.

**Comment by f2bo** [comment]
Hi @boyofgreen 

> @f2bo am I remembering that there might be some periodic cleanup to do in cloudAppx ?

Not in CloudAppX, at least in theory. It should clean up any temporary files after the app package is generated. It should also handle an abnormal termination although there's always the possibility that some failure condition wasn't taken into account.

**Comment by boyofgreen** [comment]
thiss should be fixed up uping version to match CLI

**Comment by AmazingJaze** [comment]
@boyofgreen @f2bo How does the versioning for the instance of ManifoldJS that the WebSite uses get managed? 

From what I can gather, the ManifoldJs-site doesn't list ManifoldJS as a dependency in its [Package.json](https://github.com/manifoldjs/manifoldjs-site/blob/master/package.json) so I assume it must get deployed somehow separately?

I've verified that this issue (#218) no longer repro's with ManifoldJS 0.7.1 but if we believe that the root cause was that the version on the website and the version on npm getting out of sync, it would be nice to have the website just always grab and use the latest version from npm each time it gets deployed. 

This could also afford an opportunity to use [GreenKeeper.io](https://greenkeeper.io/#how-it-works) to monitor ManifoldJS-site dependency on ManifoldJS and automatically run tests or open an issue to redeploy ManifoldJS-site (if we desire) whenever a new version of ManifoldJS is released, if ManifoldJS-site isn't already listing the latest version as a dependency.

___
If we get a big push of new users with for an upcoming release of ManifoldJS, I think its important that anyone be able to play with the tool at manifoldjs.com/generator and then immediately use the output from that in ManifoldJS command line tool to package their app, anything less is going to feel like a broken promise to anyone who was excited to try out our tech.
