### ISSUE TITLE
Default badge images provided by manifoldjs for Windows Apps, fail the Windows store submission

### ISSUE THREAD

**Issue by AmazingJaze** [manifoldjs/ManifoldJS#219]
The Windows store submission only allows badge images to contain white or transparent colors. The 2 default badge images provided by manifoldjs when an app does not provide a manifest, contain other colors. 

Submitting any app using these images, to the Windows Dev Center for store submission fails the submission process.

![image](https://cloud.githubusercontent.com/assets/6732159/17826204/3e540e2a-6623-11e6-8051-5110ec333f1f.png)

**Comment by AmazingJaze** [comment]
Ideally, submitting a manifold generated package to the store would just work. 

When looking through the generated manifest and appxmanifest, the only place I can see images/BadgeLogo.png referenced is in windows10/appxmanifest.xml. 

![image](https://cloud.githubusercontent.com/assets/6732159/17827466/46fee9a0-6632-11e6-8210-b2341625246a.png)

I assume the windows store must require all apps to include a  lockscreen badge icon? I'm not able to test it by modifying my source and resubmitting at the moment.

**Comment by AmazingJaze** [comment]
I removed the Badge Icon from my manifest before repackaging and resubmitting to the windows store this morning. Should be at least a day to get results back.

In the mean time I compared this to the package output generated by Windows App Studio, and it would appear they don't even include a `<uap:LockScreen />` tag in the appxmanifest.xml when the input URL doesn't provide a web manifest. I can also confirm that I've already previously submitted their package to the successfully, so it would appear that badge icon's are not a requirement and manifold could just remove it from the generated windows 10 manifest as a work around to pass the store's certification check.

That being said, its nice to be able to demo the lock screen badge functionality in cases like this where user's don't already have one. @boyofgreen do you or @f2bo have the resources to generate a monochromatic version of the current badge icon?

**Comment by boyofgreen** [comment]
we don't have a way to make it images non-rgba yet, but it's in the roadmap.    So we do have a transparent BG, but I guess it needs to just be black and white.  I think the easy fix is to make the default image black and white for that size.  Wouldn't that be prefered to removing it?

**Comment by marcoscaceres** [comment]
Related: https://github.com/w3c/manifest/issues/480

**Comment by AmazingJaze** [comment]
@boyofgreen Just to be clear, it appears the error is that the badge icons are red and transparent. If we were to use white and transparent images instead, that should resolve the problem and would be preferable to removing badge icons.

**Comment by boyofgreen** [comment]
I think we can move the default image for the badge to black and white for now, then add a check in later during download to check the image for windows10.  if the W3C spec takes in badge, we will follow them of course.

**Comment by boyofgreen** [comment]
We are likely doing a small windows10 releaes next week, we can get the first change in that.

**Comment by AmazingJaze** [comment]
Is there still chance of a release this week?

**Comment by msrodri** [comment]
We'll be including this fix in the next release
