### ISSUE TITLE
Fails silently when you get the casing of a platform name wrong

### ISSUE THREAD

**Issue by stkb** [manifoldjs/ManifoldJS#220]
Just had a couple of minutes head scratching after I was using the command: `manifoldjs -m manifest.json -p Windows10` (note `Windows10` instead of `windows10`).

It turns out entering a garbage platform name gives an error. But giving a platform name that is correct apart from the casing, causes the manifest to be validated, and a folder for the project to be created, but no folder for the platform underneath that, and no error message.

The platform name input should preferably be case-insensitive, or at least give an error if the casing is incorrect.

**Comment by boyofgreen** [comment]
Thanks @stkb and sorry about that, we'll work to make it more robust... or at least give better errors!  We should be able to at least pull up a list of your installed platforms and suggest one of them.
