### ISSUE TITLE
Use remote web app api within cordova

### ISSUE THREAD

**Issue by TarStry** [manifoldjs/ManifoldJS#241]
Do you know of a way to do this oppositely, by which I mean add interactive elements to a cordova app that connect to the hosted site's api. I currently have a cordova app that simply serves a web-site to a user after showing the splashscreen, and would like to add app specific elements that perform calls on that website. Things such as adding an app specific navigation bar that allows for printing the current page from within the app, or taking a screenshot from the device without having to change the site code.

**Comment by boyofgreen** [comment]
Hi @TarStry  Sorry I missed this coming in last month.  This should help you get that done if you haven't found it already

https://github.com/manifoldjs/ManifoldJS/wiki/Using%20Cordova%20Plugins%20in%20Hosted%20Web%20Apps
Thanks,
Jeff
