### ISSUE TITLE
transparent and hex is not a valid color for windows warning

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#244]
Generator:
http://manifold-site-pre.azurewebsites.net/generator

with test site: http://www.msn.com
Gives following warning:
Invalid value: The background color is not a valid color (#224f7b). Platforms affected: windows10.
Invalid value: The theme color is not a valid color (#224f7b). Platforms affected: windows10

These are valid, so it may be a rule that needs to be fixed or an actualy bug, but it should work.

**Comment by AmazingJaze** [comment]
I'll take a look at this one.

**Comment by boyofgreen** [comment]
fix is pushed out with version 1.0.3
