### ISSUE TITLE
trim whitespace on discription and name

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#247]
We might be doing this on name already, but we noticed a windows 10 considered the manifest incompatible because the description didn't end or start with a space.  We need to trip the description and name if not already doing it there.

**Comment by codepo8** [comment]
I take this one one

**Comment by boyofgreen** [comment]
thanks, you likely fine the fixes in these files:
https://github.com/manifoldjs/manifoldjs-lib/tree/v1.2.0-development-pwabuilder/lib/manifestTools/manifestCreator/scrapers

**Comment by codepo8** [comment]
These have been fixed and I sent pull requests

**Comment by boyofgreen** [comment]
yes sorry, I added your name to this while I was showing someone else how easy it was to add their name to an issue. I didn't think it would ping about it.   Thanks for the PRs, I'm taking them in and running test cases tonight, but I don't forsee any issues with these changes :)
