### ISSUE TITLE
"generate icons from image" in image generatior shoul d return larger images

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#250]
We want to return the 200 size images (like vs does) for win10 and find any key size for other platforms.  This is a simple JSON file update:
https://github.com/manifoldjs/App-Image-Generator/blob/master/AppImageGenerator/App_Data/manifoldjsImages.json

 but WIn10 project is already trained for these images so we need to do this as well: 
 you will need to add the default 200 scale images in the Windows-10 assets/images directory.

**Comment by rnrneverdies** [comment]
Fixed. It will be available in the next major release.
