### ISSUE TITLE
WkWebView support

### ISSUE THREAD

**Issue by suur** [manifoldjs/ManifoldJS#269]
In 0.5.2 release notes, there is a known issue.

> Even though Cordova iOS@4.0 introduces pluggable webviews, the Hosted Web App plugin currently supports UIWebView only. WkWebView will be supported in a future release.

When is WkWebView support planned? Is there an easy way to fix this? Any help would be appreciated.

**Comment by boyofgreen** [comment]
Hi @suur you can change it by editing the plist of the generated iOS app.  I've done this before in an app without seeing any problems.  We don't have as many resources who are interested in updating the plugin, hence the slow cycles.  We are always open to PRs!   Thanks, and hope it works out for you.  -jeff

**Comment by bhollis** [comment]
@boyofgreen what edit should we make to the generated iOS app's plist in order to achieve this?
