### ISSUE TITLE
ERR! 404 'ManifoldJS' is not in the npm registry.

### ISSUE THREAD

**Issue by marcoscaceres** [manifoldjs/ManifoldJS#27]
➜  ~  npm install -g ManifoldJS
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ManifoldJS"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code E404

npm ERR! 404 Not Found: ManifoldJS
npm ERR! 404
npm ERR! 404 'ManifoldJS' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marcos/npm-debug.log

**Comment by marcoscaceres** [comment]
here is the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ManifoldJS' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ 'ManifoldJS', null ]
6 verbose cache add spec ManifoldJS
7 silly cache add parsed spec { raw: 'ManifoldJS',
7 silly cache add   scope: null,
7 silly cache add   name: 'ManifoldJS',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed ManifoldJS@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'ManifoldJS', range: '*', hasData: false }
12 silly mapToRegistry name ManifoldJS
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ManifoldJS
16 verbose addNameRange registry:https://registry.npmjs.org/ManifoldJS not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ManifoldJS
18 verbose request no auth needed
19 info attempt registry request try #1 at 19:23:35
20 verbose request id 0d28c97bc8423f1f
21 http request GET https://registry.npmjs.org/ManifoldJS
22 http 404 https://registry.npmjs.org/ManifoldJS
23 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 verbose headers   'content-type': 'application/json',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   'content-length': '51',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Thu, 30 Apr 2015 23:23:36 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   age: '0',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-fra1229-FRA',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1430436215.595236,VS0,VE431' }
24 silly get cb [ 404,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=0',
24 silly get     'content-length': '51',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Thu, 30 Apr 2015 23:23:36 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-fra1229-FRA',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1430436215.595236,VS0,VE431' } ]
25 verbose stack Error: 404 Not Found: ManifoldJS
25 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:245:14)
25 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
25 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:360:22)
25 verbose stack     at Request.emit (events.js:110:17)
25 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1202:14)
25 verbose stack     at Request.emit (events.js:129:20)
25 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1150:12)
25 verbose stack     at IncomingMessage.emit (events.js:129:20)
25 verbose stack     at _stream_readable.js:908:16
25 verbose stack     at process._tickCallback (node.js:355:11)
26 verbose statusCode 404
27 verbose pkgid ManifoldJS
28 verbose cwd /Users/marcos
29 error Darwin 14.3.0
30 error argv "node" "/usr/local/bin/npm" "install" "-g" "ManifoldJS"
31 error node v0.12.2
32 error npm  v2.7.5
33 error code E404
34 error 404 Not Found: ManifoldJS
34 error 404
34 error 404 'ManifoldJS' is not in the npm registry.
34 error 404 You should bug the author to publish it (or use the name yourself!)
34 error 404
34 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]

**Comment by nbellocam** [comment]
Sorry, this was a mistake in the Readme. The npm package is manifoldjs, not ManifoldJS. Link: https://www.npmjs.com/package/manifoldjs.

Thanks!

**Comment by boyofgreen** [comment]
Nicholas, Do you know if there way to publish it under both?  I don't want to maintain two different packages, but I don't know if there is any way to alias it or not.  do you know?

**Comment by marcoscaceres** [comment]
Ok, all lowercase works :)

**Comment by nbellocam** [comment]
I'm not aware of any way to have a package alias in npm (couldn't find any example nor documentation about this). I'm not sure if it would be a good idea to have two different packages. Ideally, we should update the documentation only to point to manifoldjs.

I will close this issue for now as the main documentation is already fixed.
