### ISSUE TITLE
Manifest validation fails after resolving the "display" W3C property

### ISSUE THREAD

**Issue by msrodri** [manifoldjs/ManifoldJS#270]
When the builder is creating a manifest of a site and infers that the `display` is **fullscreen**, **standalone** or **minimal-ui**, it retrieves the value **true** instead which is an invalid value for `display`.

The builder then fails during the manifest validation stage with the following error:

`[error] general     : Manifest validation ERROR      - No enum match for: true(member: /display)`

This can be reproduced on the http://politiken.dk/ site

**Comment by rnrneverdies** [comment]
Fixed, will be available in the next major release.
