### ISSUE TITLE
Domain mismach validation error with redirect URLs

### ISSUE THREAD

**Issue by msrodri** [manifoldjs/ManifoldJS#272]
When the builder uses URL http://pol.dk, it gets redirected to http://politiken.dk

Since the site has no manifest, the builder creates a manifest extracting the start URL from the following metadata within the page:

`<meta name="msapplication-starturl" content="http://politiken.dk" />`

Then, the following validation error is thrown:

`The domain of the hosted site (pol.dk) does not match the domain of the manifest's start_url member (politiken.dk)`

**Comment by msrodri** [comment]
As discussed with @boyofgreen, it is OK to have this validation. We should make sure the error message is properly shown in both the CLI and the Generator Web site

**Comment by rnrneverdies** [comment]
Fixed. It will be available in the next major release.
