### ISSUE TITLE
Android permission

### ISSUE THREAD

**Issue by leyenda** [manifoldjs/ManifoldJS#273]
Hello, my web App uses the camera and the geolocation. How can I give those permissions to my android app generated by manifoldjs. Tried adding the corresponding permissions on  AndroidManifest.xml  but neither the camera and the geolocation is working. How can I achieve this?

Thanks

**Comment by boyofgreen** [comment]
i think this will help
https://github.com/manifoldjs/ManifoldJS/wiki/Using-Cordova-Plugins-in-Hosted-Web-Apps
