### ISSUE TITLE
Allow to use Crosswalk for building for Android

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#29]
Cordova 4.x supports using the Crosswalk runtime (http://www.crosswalk-project.org) as the "webview" which ensures a consistent user experience across any device running Android from 4.0 and up.

**Comment by boyofgreen** [comment]
Hey Kenchris,
  I have had this request before, we'll add it to the back log and make it an option.

**Comment by kenchris** [comment]
Maybe @r0b5t4 is interested in helping or providing pointers

**Comment by kenchris** [comment]
@r0b5t4 created this: https://github.com/r0b5t4/crosswalk-app-tools (apache license)

**Comment by msrodri** [comment]
We are moving this issue to [release-0.2.0](https://github.com/manifoldjs/ManifoldJS/milestones/release-0.2.0), where the tool will support codova-android 4.0.

Since this change requires cordova-android 4.0 (see this [link](https://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html)) it will make sense to address this issue in that release of manifoldjs.

**Comment by f2bo** [comment]
We've started exploring using Crosswalk in ManifoldJS and are looking for good test cases. Does anyone have any recommendations for existing sites that would benefit from switching to Crosswalk?

**Comment by kenchris** [comment]
The benefit is bigger on older versions of Android as they are running a WebView not based on Chromium or Blink (but WebKit based).

Also any site using canvas 2D or 3D (WebGL) or any newer web feature.

You could try some of the below:

https://jakearchibald.github.io/svgomg/
https://wiki-offline.jakearchibald.com/
https://voice-memos.appspot.com/
http://webglsamples.googlecode.com/hg/aquarium/aquarium.html
http://webglsamples.googlecode.com/hg/dynamic-cubemap/dynamic-cubemap.html
http://ie.microsoft.com/testdrive/performance/fishietank/?o=1
http://ie.microsoft.com/testdrive/mobile/Performance/Galactic/Default.html
http://peterjensen.github.io/mandelbrot/js/mandelbrot-xdk.html (Crosswalk supports SIMD on Intel Architecture)
https://photos.google.com

**Comment by f2bo** [comment]
Thanks for the suggestions @kenchris. Very helpful. 

We've now included an optional command line argument in ManifoldJS that you can use to enable Crosswalk. It should be available in the next release. (see https://github.com/manifoldjs/ManifoldJS/commit/b4de577c7e86f25104eda48295c4a3e43c742461) 

Looking forward to some feedback.

**Comment by kenchris** [comment]
The Crosswalk support is not mentioned in the documentation: http://manifoldjs.com/documentation

Could that be fixed?
