### ISSUE TITLE
<website-url> shouldn't be required if the -m is used and the start_url is an absolute URL

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#30]
<website-url> shouldn't be required if the -m is used and the start_url is an absolute URL

**Comment by boyofgreen** [comment]
We also use the website name for a few other things like the android name space, but that could be derived from the start URL.
  I don' t see any issue with putting this on the backlog

**Comment by msrodri** [comment]
We updated the CLI tool to make <website-url> optional in this particular scenario.
