### ISSUE TITLE
Capabilities support in manifest

### ISSUE THREAD

**Issue by nbellocam** [manifoldjs/ManifoldJS#40]
This discussion is based on the comments from issue #31.

Let's continue discussing about this topic in this new issue.

From @marcoscaceres:

 > For capabilities (again because of our focus on Web browsers), we were not able to find non-proprietary APIs that required a capabilities declaration (hence why they are missing from the spec right now).

From @kenchris:
 > Regarding capabilities:

 > With the permission spec (non-upfront permissions) this seems like a thing that will go away
Permissions differ a lot per platform
 > Due to these reasons, I think it is best that the tool will figure out what permissions to enable per platform.

 > AFAIU, I can use the Windows object on Windows and you will implement parts of that for other platforms using Cordova? Or Is it possible to use the Cordova APIs directly?

 > I think that we should create a msj_ extension here, but I need to find out exactly how all of this works in order to help you design such an extension :-)

 > If you support the Core Cordova APIs, we could add something like

 > `"msj_cordova_plugin": ["battery-status", "contacts"]`

 > where the name is taking from the plugin name itself (ie "org.apache.cordova.battery-status"). For each platform you already know which permissions each plugin requires.

 > If you don't support the Cordova APIs directly and just emulated Windows object, then we should find another solution. I kind of like the ability to use the core Cordova APIs though, as many hybrid apps do that already, like Untappd.

**Comment by kenchris** [comment]
I am pretty sure that we [The Crosswalk Project] would also want to allow hosted/packaged apps to access the Cordova core APIs for apps packaged with Crosswalk (adding @baleboy, @anssiko) so maybe this could be just "cordova_plugin" or similar.

@marcoscaceres and me talked about adding a link in the Web App Manifest spec to refer to a wiki page where we would list all common manifest extensions for these kinds of scenarios.

**Comment by marcoscaceres** [comment]
Agree, there are probably going to be quite a few projects relying on this so would be good to work out naming, etc.

**Comment by boyofgreen** [comment]
we will join into the discussion on the spec page if we get more feedback from users.  Other wise, feel free to open an issue for us if there is an action for us
