### ISSUE TITLE
Generator Not Working?

### ISSUE THREAD

**Issue by johnshew** [manifoldjs/ManifoldJS#42]
There are some comments in Hacker News that people have tried the generator from manifoldjs.com and reporting that it isn't working.

I just did a quick test and it didn't come back.  Might want to check into this.

**Comment by nbellocam** [comment]
Thanks for reporting this. Hacker News link: https://news.ycombinator.com/item?id=9487941

**Comment by nsbingham** [comment]
@johnshew if you don't mind me asking, what URL were you using when it failed?

**Comment by johnshew** [comment]
I don't know what the person on Hacker News was seeing.  

Here is the quick test I tried.  Just went to http://www.manifoldjs.com/generator.

Entered bing.com as the web site.  Hit next.  Gave it the name Bing.  And hit generate package.  Spins.  Nothing happens. 

It indicates "building package" but then nothing - no package, no error message.

**Comment by iCityWork** [comment]
I am not able to use it either, I go to http://www.manifoldjs.com/generator and enter all the info required, I get 0 errors and 0 warnings, 1 suggestion 
{
mjs_urlAccess
Required value: It is recommended to specify a set of access rules that represent the navigation scope of the application. Platforms affected: all.
}

Hit Generate and it acts like it is going to do something but never spits out the file.

Help?
Gavin

**Comment by nsbingham** [comment]
@johnshew Some updates were pushed to the site that have hopefully fixed the issue you were experiencing.

@iCityWork Would you mind sharing what browser you're using and the URL for which you're trying to generate a package?

**Comment by iCityWork** [comment]
@nsbingham I am using Chrome Version 42.0.2311.135 m 
last tried about 30 min ago.

**Comment by boyofgreen** [comment]
I received a similar issue tonight. I tried with Bing.com 4 times, and it failed for one of them. And when it failed, no error message or anything.

**Comment by boyofgreen** [comment]
I was using ie11 on windows 8.1

**Comment by johnshew** [comment]
After a couple of experiments it appears that the generate step fails silently if you fail to have mjs_urlAccess defined.

This is significant for at least two reasons:

* We should require mjs_urlAccess - instead if it is needed and missing is should default to initial URL provided.  

* Failing silently is bad behavior.  Recommend we should have some sort of developer status while the generate step is happening - maybe just show the -l debug output.

**Comment by johnshew** [comment]
Opps I accidently closed this issue.

**Comment by whokilledtheelectricmonk** [comment]
Should be more explicit about the format for scope. Does it take a list? Regex? I found that using / as the scope loaded a black page on Android, but relative paths are shown on the W3C example. Ultimately it seems that * should be the default value.

**Comment by marcoscaceres** [comment]
"*" is not a valid default: that will just default to "http://example.com/*/" (literally * path).

**Comment by marcoscaceres** [comment]
(argh, fixed comment above... it ate my :star:s)

**Comment by marcoscaceres** [comment]
Fixed bug on the spec to add more examples of scope: 
https://github.com/w3c/manifest/issues/380

**Comment by whokilledtheelectricmonk** [comment]
Sounds like there may be differing implementations of scope. When I built for Android, I got a page with no CSS or images if I used `/`, plus no way to navigate off page. I got a page with no images (served over Cloudfront so off-domain) if I used the `https://domain.com/*`. When I set the scope to `*` it worked as expected.

**Comment by marcoscaceres** [comment]
@whokilledtheelectricmonk whoa, strange. Is that for a generated package for Android? Can you provide a bit more details?

**Comment by whokilledtheelectricmonk** [comment]
Just checked on iOS - same result. The only way off-domain resources are loaded is to provide `*` in the scope field.

**Comment by msrodri** [comment]
I created a [new issue](https://github.com/manifoldjs/ManifoldJS/issues/60) for the discussion about how manifoldjs processes the scope variable

**Comment by ryanbillingsley** [comment]
The generator should now let you know if the build failed and provide any error information it has.
