### ISSUE TITLE
Provide more details when an invalid manifest format is detected

### ISSUE THREAD

**Issue by nbellocam** [manifoldjs/ManifoldJS#43]
This issue is based on a discussion on issue #28.

From @kenchris:  
 > I guess getting as much right info out of the invalid manifest makes sense and issuing warnings instead. That way people would know how to contact cnet.com (if it is not them packaging up their own site :))

We could add a way to specify the kind of manifest used in order to retrieve more information or be more flexible with the manifest detection logic

**Comment by brandonros** [comment]
```
{
  "start_url": "http://google.com/",
  "short_name": "Google",
  "icons": [],
  "display": "fullscreen",
  "orientation": "any",
  "name": "Google",
  "description": "Search the web.",
  "version": "1.0",
  "build": "1",
  "publishername": "Google",
  "organizationid": "Google"
}
```

➜  ~  manifoldjs http://google.com/ -p ios -b -m manifest.json
ERROR: Invalid manifest format.

**Comment by nbellocam** [comment]
@brandonros I created a new issue (https://github.com/manifoldjs/ManifoldJS/issues/44) for what you reported.

**Comment by boyofgreen** [comment]
Can we close this issue since we have #44 open?

**Comment by nbellocam** [comment]
Just for clarification, issue #44 is an issue related to the website which is not adding the prefixes in the manifest. This target an enhancement opportunity to show more details when the manifest is not valid and its related to the tool.

**Comment by f2bo** [comment]
We are now taking advantage of the JSON schema for the W3C manifest format (http://json.schemastore.org/web-manifest) to provide additional information when a manifest contains errors (see https://github.com/manifoldjs/ManifoldJS/pull/87).

For example, the manifest at http://www.cnet.com currently has several issues with the icons element, including using the keyword **_size_** instead of **_sizes_** as well as defining the **_density_** member as a string instead of a number. 
```
{
    "short_name": "CNET",
    "name": "CNET",
    "icons": [
        {
            "src": "bundles/cnetcss/images/core/logo_32.png",
            "size": "32x32",
            "type": "image/png",
            "density": "0.75"
        },
        {
            "src": "bundles/cnetcss/images/core/logo_48.png",
            "size": "48x48",
            "type": "image/png",
            "density": "1.0"
        },
        {
            "src": "bundles/cnetcss/images/core/logo_72.png",
            "size": "72x72",
            "type": "image/png",
            "density": "1.5"
        },
        {
            "src": "bundles/cnetcss/images/core/logo_96.png",
            "size": "96x96",
            "type": "image/png",
            "density": "2.0"
        },
        {
            "src": "bundles/cnetcss/images/core/logo_192.png",
            "size": "192x192",
            "type": "image/png",
            "density": "4.0"
        }
    ],
    "display": "standalone",
    "start_url": "http://www.cnet.com/?homepage=1&setDevice=mobile"
}
```

As a result of the JSON schema validation, ManifestJS currently shows the following output for this site:
``` 
ERROR: Manifest validation  (All Platforms) - Invalid type: string (expected number)[/icons/0/density]
ERROR: Manifest validation  (All Platforms) - Invalid type: string (expected number)[/icons/1/density]
ERROR: Manifest validation  (All Platforms) - Invalid type: string (expected number)[/icons/2/density]
ERROR: Manifest validation  (All Platforms) - Invalid type: string (expected number)[/icons/3/density]
ERROR: Manifest validation  (All Platforms) - Invalid type: string (expected number)[/icons/4/density]
WARNING: Manifest validation  (All Platforms) - Unknown property (not in schema)[/icons/0/size]
WARNING: Manifest validation  (All Platforms) - Unknown property (not in schema)[/icons/1/size]
WARNING: Manifest validation  (All Platforms) - Unknown property (not in schema)[/icons/2/size]
WARNING: Manifest validation  (All Platforms) - Unknown property (not in schema)[/icons/3/size]
WARNING: Manifest validation  (All Platforms) - Unknown property (not in schema)[/icons/4/size]
```
