### ISSUE TITLE
Website is generating invalid manifests

### ISSUE THREAD

**Issue by nbellocam** [manifoldjs/ManifoldJS#44]
Moving this to a new issue:

from @brandonros:
 > ```
 > {
 >   "start_url": "http://google.com/",
 >   "short_name": "Google",
 >   "icons": [],
 >   "display": "fullscreen",
 >   "orientation": "any",
 >   "name": "Google",
 >   "description": "Search the web.",
 >   "version": "1.0",
 >   "build": "1",
 >   "publishername": "Google",
 >   "organizationid": "Google"
 > }
 > ```
 > File generated directly from website.

 > ➜  ~  manifoldjs http://google.com/ -p ios -b -m manifest.json
 > ERROR: Invalid manifest format.

**Comment by brandonros** [comment]
Is there any more information I can provide?

**Comment by nbellocam** [comment]
You added the App Store Details, right? There seems to be some issues when filling the fields in that section of the _Generate_ page in the website. 

In the meantime, if you want to workaround this, just don't fill these fields.

**Comment by brandonros** [comment]
Is the compile feature working on the site? I saw a separate issue where it was flagged as not working, and I couldn't get it to work myself.

I can't figure out how to change the icons or project name.

**Comment by whokilledtheelectricmonk** [comment]
When downloaded and run with node, I get an `invalid manifest format` error when I include the `description` and `publishername` fields. Changing to `publisher_name` works, but nothing (including using an empty string for the value) fixes the error for `description`.

**Comment by boyofgreen** [comment]
Generally we want these to be prefixed, for us to read them it would be mjs_, but you can provide your own prefix.  However, I think we can move these to warnings rather than errors.  There is no need to break the build

**Comment by ryanbillingsley** [comment]
The App Store Details section has been removed from the generator.  This should help avoid any further confusion.

**Comment by kenchris** [comment]
You could prefix them with msj_ if these are of value to you, or file bugs to the Web App Manifest spec if you believe that these should be in the spec

**Comment by ryanbillingsley** [comment]
Going to close this but re-open if you are still seeing issues.
