### ISSUE TITLE
Support for splashscreens member (W3C)

### ISSUE THREAD

**Issue by marcoscaceres** [manifoldjs/ManifoldJS#45]
Just a heads up that we've added a [`splashscreens` member](https://w3c.github.io/manifest/#splash_screens-member) to the W3C Web Manifest spec. However, we are still gathering implementer feedback and we currently don't have strong commitment from any vendor to support them (i.e., please don't add them to ManifoldJS just yet! :smile:).

Will report back with more info soon. Design wise, they take the exact same object as `icons` (an array of image objects), so validation/transformation will be identical.

**Comment by nbellocam** [comment]
Thanks for sharing this! We will add it to the backlog to keep it tracked.

**Comment by boyofgreen** [comment]
Marcos,
  I believe I saw Firefox add some tasks for supporting the splashscreens member.  I'm still planting to hold off a bit for it to solidify, but let me know if you think we should move forward sooner.

**Comment by marcoscaceres** [comment]
Hold for a bit, I haven't gotten a straight answer out of the Google guys if they are going to support it or not (need to also check with Microsoft).

**Comment by boyofgreen** [comment]
Double check with Alex lu, but from the MS side it seems to make sense for us.

**Comment by marcoscaceres** [comment]
@boyofgreen great to hear. Will ping Alex also.

**Comment by boyofgreen** [comment]
i think we are now ready to implement this, it is a great add

**Comment by marcoscaceres** [comment]
@boyofgreen, sounds good. Please note that there are some ongoing discussions over at the w3c: 

 * how should we set the background color of the splash screen? https://github.com/w3c/manifest/issues/390
 * Should we support 9-patch images for splash screens? https://github.com/w3c/manifest/issues/373
 * should the developer or the user agent control when the splash screen is removed? https://github.com/w3c/manifest/issues/372 
 * What should happen if starting the application can happen in less than ~300-500ms? Should the splash screen still be shown or just a background color? (proposed in https://github.com/w3c/manifest/issues/390)

We would really appreciate ManifoldJS team's feedback.

**Comment by f2bo** [comment]
As far as I can tell, there isn't support for splash screens in either Firefox or Chrome apps at the moment. 

So, for the time being, this applies only to the Cordova-based apps generated by ManifoldJS and should be implemented in the ManifoldCordova plugin (cordova-plugin-hostedwebapp).

I've created a new issue in the plugin's repository to track this (https://github.com/manifoldjs/ManifoldCordova/issues/37).

**Comment by msrodri** [comment]
We added support for the W3C `splash_screeens` member in ManifoldCordova plugin (see https://github.com/manifoldjs/ManifoldCordova/commit/07fda20ac70012f7ee0dd88ed01b26c419547a52).

**Comment by kenchris** [comment]
Just a heads-up. It seems that Chrome have chosen not to use the splash_screen and just generate splash screens from the 'background_color' plus an appropriate square icon from 'icons'

They are hiding the splash on first paint.

@marcoscaceres @anssiko

**Comment by kenchris** [comment]
https://developers.google.com/web/updates/2015/09/using-web-app-manifest-to-set-solid-color-loading-screen

https://chromium.googlesource.com/chromium/src/+/1be62c2b7f12a4a8108d3b23b479059c706ffc09
