### ISSUE TITLE
Needs examples

### ISSUE THREAD

**Issue by GeoffreyPlitt** [manifoldjs/ManifoldJS#46]
Are there any open-source boilerplate "apps" with all the assets and the manifest setup correctly so we can test ManifoldJS and see it in action?

**Comment by kenchris** [comment]
There are plenty. Google has a web app show case page where all apps have manifests. The Google IO site is one example

**Comment by kenchris** [comment]
https://developers.google.com/web/showcase/spotlight/

**Comment by kenchris** [comment]
http://updates.html5rocks.com/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android

**Comment by boyofgreen** [comment]
A few other:
http://www.thishereweb.com
Http://tinderjstest.azurewebsites.net

**Comment by msrodri** [comment]
We just published a [Getting Started](https://github.com/manifoldjs/ManifoldJS/wiki/Getting-Started) wiki article that shows the basic workflow for creating a hosted web app using [Shiftr](http://shiftr.azurewebsites.net/) as an example.

There are plans for other examples as well. We'll keep you posted.
