### ISSUE TITLE
W3C App Manifest working group doesn't exist

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#48]
"Special thanks to the W3C App Manifest working group"

We are editing the spec as part of the WebApps working group :)

You could say: "Special thanks to the W3C Web App Manifest editors and the W3C WebApps Working Group"

**Comment by nbellocam** [comment]
Thanks for reporting this. The issue can be found in the _Who created manifoldJS_ of the [community](http://www.manifoldjs.com/community) page.

**Comment by boyofgreen** [comment]
I can make a change to the site next week.

**Comment by ryanbillingsley** [comment]
@kenchris this should be fixed now
