### ISSUE TITLE
https://events.google.com/io2015/manifest.json doesn't get parsed

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#49]
It has some chrome_ extensions which should be fine.

**Comment by nbellocam** [comment]
This issue is already fixed in [v0.1.3](https://github.com/manifoldjs/ManifoldJS/tree/v0.1.3). However, there is another issue with that site. I created a [new issue](https://github.com/manifoldjs/ManifoldJS/issues/52) for that one.
