### ISSUE TITLE
Running manifoldjs without arguments could be more informative

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#50]
$ manifoldjs 
: No such file or directory

**Comment by nbellocam** [comment]
You are running manifoldjs in Linux and installed from npm, right? This is related with issue https://github.com/manifoldjs/ManifoldJS/issues/35.

The tool provides the following output if you use it without parameters:

![screen shot 2015-05-07 at 12 05 40 pm](https://cloud.githubusercontent.com/assets/1168065/7518487/9f46a02e-f4b1-11e4-8e59-1b1302c1875c.png)

I will close this issue for now. Thanks!

**Comment by kenchris** [comment]
Yes, linux, installed from npm

**Comment by kenchris** [comment]
Actually you should probably include the documentation url in that output
