### ISSUE TITLE
Getting Window height and width

### ISSUE THREAD

**Issue by jpmonette** [manifoldjs/ManifoldJS#51]
In my existing Website, I'm getting specific container size to automatically fill up the whole screen with an image (using `$(window).height()` and `$(window).width()`). It doesn't return any value when wrapped using ManifoldJS on Android.

Also, the `$( window ).resize(function() {` doesn't seem to work.

Any clue how to do something similar?

**Comment by kenchris** [comment]
You need to provide more information, like what platform are you talking about (Windows 10? Android?). Also notice that the $() is a jQuery method so you need to use jQuery for it to work.

**Comment by jpmonette** [comment]
I've built an APK for Android 21.0 API. I do have the jQuery library included in my Webpage. When I go form the browser, everything works fine. I also tried to use an alert to display the window width. It does work on the browser, but it doesn't display anything on the mobile version.

**Comment by kenchris** [comment]
On Android windows are always take up the full screen realestate (expect status bar, buttons etc) and the other option is going into fullscreen. So resizing the window should not be possible, though you can set it it fullscreen in the manifest.json.

As far as I understand window.window.width should return undefined for non popups (it does so in Chrome), so there is another way to get the value you want:

window.innerWidth and window.outerWidth. If you add a viewport meta with width=device-width (no content scaling) these should be the same as Android adds no border to the window.

**Comment by jpmonette** [comment]
I want to know the full height/width of the current view to know how to display HTML containers, since all devices have different sizes, and if you change from landscape to portrait mode, the width and height will also change (I want to be able to resize stuff when the user rotate his device).

I have the following in my meta tags:

``<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />``

I have the following later in my JavaScript (that's the only thing I have):

``<script>document.body.innerHTML = window.innerWidth</script>``

When I open the page in a browser, it is showing me the width of the browser view. When I open it in my Chrome Android browser, I get the width too. When I open it inside an application generated by ManifoldJS, I get a blank page. It should technically display the width, unless I'm missing something.

Any clue?

**Comment by kenchris** [comment]
Btw, a better way to layout things is to use vw/vh units :-) there are 100 viewport width units (vw) per width, and 100 viewport height units (vh) per height.

**Comment by jpmonette** [comment]
How can I access viewport from JavaScript and reposition elements?

**Comment by boyofgreen** [comment]
On Android you are in a webview so they will have a few of differences when it comes to reading the viewport.  What you want in this case I believe is the CSS pixels.  For that I believe document.body.clientWidth and clientHight will give you the values you need.
  Another option might be to set it using css, and in that case you can use the device-width / device-height media queries.  Hope that helps

**Comment by boyofgreen** [comment]
closing the issue, let me know if you have any additional questions
