### ISSUE TITLE
iOS emulator fails to launch if name field has spaces in it

### ISSUE THREAD

**Issue by whokilledtheelectricmonk** [manifoldjs/ManifoldJS#54]
This might be a Cordova error, but this is what happens:
```
$ cd cordova
$ cordova emulate ios
(errors out because the first word is prepended to the filename somehow)
$ (remove spaces in name field in manifest)
$ cordova emulate ios
(launches app)
```

Example: `"name": "My App"`
Temp filenames: `"My My App.whatever"`
Then cordova tries to launch `My App` and can't find it

**Comment by msrodri** [comment]
Thanks for reporting this. We applied a fix to ignore space characters when the cordova apps are generated. In order for this fix to work, you need to uninstall and reinstall manifoldjs.

**Comment by goldnarms** [comment]
There might also be an issue if you have your node packages in a path with a space (as I do). Please see my stackoverflow question: http://stackoverflow.com/questions/30177174/failing-to-create-package-with-manifoldjs

**Comment by msrodri** [comment]
I created a [new issue](https://github.com/manifoldjs/ManifoldJS/issues/57) to track the problem with spaces in the node installation path.

I'll close this issue for now.

**Comment by whokilledtheelectricmonk** [comment]
Thanks, seems like it worked when I rebuilt after reinstall.
