### ISSUE TITLE
Provide more details when createApps() fails

### ISSUE THREAD

**Issue by ryanbillingsley** [manifoldjs/ManifoldJS#56]
Current when this function fails, all we get back is

`Error: One or more errors occurred when generating the application.`

But no mention of what those errors actually were.

**Comment by f2bo** [comment]
The following is currently in the 0.1.4 branch.

We updated **createApps** to provide additional diagnostic information to callers when one of its operations fails. Now, the callback receives an enhanced Error object with a message indicating the operation that failed. This error object may include an **innerErrors** property (an array) with one or more errors providing detailed information about the cause of the failure. If the error happens deep inside a library function, these inner errors may themselves contain other inner errors allowing the consuming code to traverse the nested hierarchy to obtain the necessary details and create a diagnostic report. 

In addition, we updated **createApps** to perform the validation of the manifest and to return an Error object with a name of ‘**ValidationError**’  whenever a validation rule with a level of ‘_error_’ fails. For convenience, this object contains a **validationResults** property with the result for each validation rule. Note, however, that rules with a level of ‘_warning_’ or ‘_info_’ do not result in a fatal error.
