### ISSUE TITLE
Add icon button confusion

### ISSUE THREAD

**Issue by Gr8Gatsby** [manifoldjs/ManifoldJS#59]
could we only make the add icon button enabled when there is a valid URL in the icon box?  The default values seem to be implemented incorrectly?

**Comment by ryanbillingsley** [comment]
@Gr8Gatsby which default values are you referring to?

The icon box will support both absolute and relative urls.  If you are using relative urls, then it will base that off the current `start_url`.

**Comment by Gr8Gatsby** [comment]
The Icon URL field has a default value that doesn't look like placeholder text.  Normally the placeholder text would be more obvious, greyed out text color, and potentially even italic.  This was confusing on first use please fix it.

The other aspect is that the Add Icon Button is able to be pressed when there is a placeholder value, it should be disabled until I've enter an actual URL.

**Comment by ryanbillingsley** [comment]
@Gr8Gatsby what browser are you using?  This is what it looks like for me:

![screenshot 2015-05-13 12 02 34](https://cloud.githubusercontent.com/assets/146459/7614909/ff1c8e0e-f967-11e4-8cfc-a5d86021676b.png)

**Comment by Gr8Gatsby** [comment]
I've tested in both IE11 and Microsoft Edge.  I am guessing your screenshot is from Chrome?

**Comment by ryanbillingsley** [comment]
@Gr8Gatsby yes it is.  We will take a look at IE11 and Edge for the placeholders and see what's up.
