### ISSUE TITLE
createApps failed to add Windows Platform

### ISSUE THREAD

**Issue by ryanbillingsley** [manifoldjs/ManifoldJS#6]
Is there a prerequisite that I could be missing causing this too fail?

```
WARNING: Failed to add windows platform.
WARNING: One or more tasks failed while generating the Cordova application.
POST /manifests/89a4eb57-ed04-47b6-86b2-2a023d67abaa/build 500 3786.862 ms - 1032
Error: One or more errors occurred when generating the application.
    at /Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/lib/projectBuilder.js:55:21
    at Array.forEach (native)
    at /Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/lib/projectBuilder.js:51:17
    at _fulfilled (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/q/q.js:756:13)
    at /Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/q/q.js:564:44
    at flush (/Users/ryanbillingsley/Dev/manifold-api/node_modules/manifoldjs/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by msrodri** [comment]
Are you running the API in an environment different than Windows? Unfortunately, Cordova apps for the Windows platform can only be generated in Windows OS. If you plan to deploy the site in Azure Websites, you will not have this issue as you will be running in a Windows environment.

As a workaround for your testing purposes (e.g. if you are using Mac OS or Linux), you may want to remove 'windows' from the platforms parameter passed to the createApps method.

BTW, let us know if you have any suggestion regarding the way the API sends the error to the callback method, in case you prefer to handle this type of errors in some particular way.

**Comment by ryanbillingsley** [comment]
@msrodri will this be true of the CLI tool as well?  

That would indeed be the problem I am experiencing.  I will test removing `windows` from the list of platforms.

**Comment by msrodri** [comment]
Yes, this will be true with the CLI tool as well. When running from the CLI tool, you can see log messages with more details about the error by using the ```-l debug``` option.
