### ISSUE TITLE
Review how manifoldjs processes the scope member of manifest.json

### ISSUE THREAD

**Issue by msrodri** [manifoldjs/ManifoldJS#60]
This issue is to review the behavior of manifoldjs with the scope member, which was raised in issue #42

**Comment by boyofgreen** [comment]
is this work already in 0.1.4?  can we close?

**Comment by msrodri** [comment]
This issue is still open, but it is the next one in the list.

**Comment by marcoscaceres** [comment]
Please let me know if anything is not clear in the spec. That part of the spec is quite new, so if something doesn't make sense or needs clarification, I'm all ears and happy to fix stuff.

**Comment by msrodri** [comment]
Thanks @marcoscaceres . After taking a look at the specs for the scope member, I have a few questions:
- Are absolute URLs considered valid for the scope value (e.g. "http://domain.com/racer" assuming that this matches the origin of the start URL) or only relative URLs (e.g. "/", or "/racer/")?
- Are wildcards ("\*") allowed as part of the scope value (e.g. "\*/\*", or "/racer/\*")?
- It is not clear what the _document URL_ means in the steps to process the [scope member](https://w3c.github.io/manifest/#scope-member). Can you clarify?

**Comment by marcoscaceres** [comment]
*  Are absolute URLs considered valid for the scope value (e.g. "http://domain.com/racer" assuming that this matches the origin of the start URL) or only relative URLs (e.g. "/", or "/racer/")?

Yes, absolutely. All URLs are resolved against the manifest's URL. I.e., the browser just does:
 
```
// manifestURL is the URL where the manifest is located, e.g., https://foo.com/manifest.json
var scope = new URL("*/*", manifestURL); 
```

*  Are wildcards ("*") allowed as part of the scope value (e.g. "*/*", or "/racer/*")?

Yes. But they don't mean anything (i.e., it's not used for any kind of wild-card matching by the implementation). For example, this is what the browser does:

```
//resolve against manifest URL
var scope = new URL("*/*", manifestURL); 
// would just give:  
"https://example.com/*/*"
```

If you have a server that serves resources from "*/*", then it will work as normal on the Web.

*  It is not clear what the document URL means in the steps to process the scope member. Can you clarify?

The document from which the manifest is acquired. So, for instance, if the application is at "http://example.com/index.html", then that is the "document URL". That URL will be different from the manifest URL, which would be at, for example, "http://example.com/manifest.json".

**Comment by marcoscaceres** [comment]
If it helps, here is my implementation of it in Gecko:
https://github.com/mozilla/gecko-dev/blob/master/dom/manifest/ManifestProcessor.jsm#L188
