### ISSUE TITLE
Can't make use of version or build number - defaults to 0.0.1

### ISSUE THREAD

**Issue by whokilledtheelectricmonk** [manifoldjs/ManifoldJS#62]
Adding a version field to the manifest breaks the generator, and adding it post-gen to the manifest in the `cordova` directory is ignored on build for iOS/Android.

**Comment by msrodri** [comment]
Can you be more explicit about this? As far as we know, version or build fields are not currently defined in the W3C specs of the Web App Manifest as a standard member. What do you expect to see by adding these fields to the manifest?

**Comment by marcoscaceres** [comment]
yeah, we don't define one in the w3c spec. We couldn't find a use case for it.

**Comment by whokilledtheelectricmonk** [comment]
Ah, well it is generated by the manifoldJS website. So I would expect the version numbers to be put in the Gradle file or something.

**Comment by msrodri** [comment]
Oh, got it. There is a section in the generator website that allows to add Store App details to the manifest (including version, build number, etc.), but this section is not currently supported. There are plans to hide that section for now and prevent breaking the generator.

**Comment by whokilledtheelectricmonk** [comment]
Ok. In that case I would find it helpful to add a Manifold-specific config file that would enable sharing of metadata between the various platforms' packages, rather than manually hunting down all the places `description`, `version`, and `publisher` need to be filled out.

**Comment by boyofgreen** [comment]
I think we have some resolution for you on this.  We have hidden that section on the generator until we figure out how it should work.  In the mean time we do allow you to add non-breaking custom values.  They will automatically be prefixed with mjs_ (unless you provide your own prefix) and you could use this for something like version number.  I'm going to close this issue, but we can reopen if it's not doing what you need.
