### ISSUE TITLE
Grunt task fails with a fatal error - Mocha exploded!

### ISSUE THREAD

**Issue by f2bo** [manifoldjs/ManifoldJS#69]
Executing **grunt** currently produces the following error:

Running "mochaTest:test" (mochaTest) task
C:\Projects\meteorite\ManifoldJS\lib\common\utils.js:2
if (typeof _$jscoverage['C:\Projects\meteorite\ManifoldJS\lib\common\utils.js'
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

>> Mocha exploded!
>> Error: BLANKET-Error parsing instrumented code: SyntaxError: Unexpected token ILLEGAL
>>     at C:\Projects\meteorite\ManifoldJS\node_modules\blanket\src\index.js:174:35
>>     at Object.blanket._blanket.instrument (C:\Projects\meteorite\ManifoldJS\node_modules\blanket\src\blanket.js:125:17)
>>     at Object.require.extensions..js (C:\Projects\meteorite\ManifoldJS\node_modules\blanket\src\index.js:155:25)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (C:\Projects\meteorite\ManifoldJS\test\common\utils.js:3:13)
>>     at Module._compile (module.js:456:26)
>>     at Module._extensions..js (module.js:474:10)
>>     at Object.require.extensions..js (C:\Projects\meteorite\ManifoldJS\node_modules\blanket\src\index.js:179:17)
Warning: Task "mochaTest:test" failed. Use --force to continue.
Aborted due to warnings.

**Comment by f2bo** [comment]
This was the result of a regression in blanket (see https://github.com/alex-seville/blanket/issues/491). We'll temporarily update the dependency in package.json to use an earlier version until this issue is fixed. Fixed by https://github.com/manifoldjs/ManifoldJS/commit/0a587cc6dc5ec505ec6f3eebc0782fcac7b91b02.

**Comment by dpundir** [comment]
It still see this issue:

if (typeof _$jscoverage['H:\code\pres-sdm\sdm\utilities\constants.js'] === 'un
                        ^^^^^^^^^^^^^^^^^^^^^^^
[SyntaxError: Unexpected token ILLEGAL]
[Error: BLANKET-Error parsing instrumented code: SyntaxError: Unexpected token ILLEGAL]

Using:
"blanket": "1.1.7"
"mocha": "2.2.5"
"grunt-mocha-test": "0.12.7"

**Comment by boyofgreen** [comment]
I'll take a look.  What OS are you running it on?

**Comment by f2bo** [comment]
Hi @dpundir. 

You seem to have upgraded the blanket package to "1.1.7", which is the one that had this problem. You need to downgrade to "1.1.6". See my previous comment for this issue.

**Comment by dpundir** [comment]
@f2bo: i wanted to report this issue not to use any workaround.
@bofofgreen: i have windows 7 64 bit os

**Comment by f2bo** [comment]
Unfortunately, the latest (published) version of blanket has a bug, which is the reason we decided to pin the dependency to 1.1.6 until they release a fix. However, the code in the master branch of the manifoldjs repository runs the tests without requiring any changes. I'm not sure I follow when you speak of workaround.

From the thread at https://github.com/alex-seville/blanket/issues/491, it would seem that there's already a fix in blanket's master branch, but it hasn't been published to npm yet. We can update the dependency when that happens but until then, I'm not sure there's much else we can do.
