### ISSUE TITLE
Failure if an existing manifest doesn't contain a start_url member

### ISSUE THREAD

**Issue by vjrantal** [manifoldjs/ManifoldJS#71]
If a W3C manifest is found from the target Web site, it is being validated for containing a `start_url` member and a `short_name` member. However, the specification doesn't seem to mandate any members to be present (http://www.w3.org/TR/appmanifest/#manifest-and-its-members).

A good default behavior in this case might be to generate the values similarly to how they are generated if the site does not have a manifest, i.e., they are implied from the given Web site URL.

**Comment by boyofgreen** [comment]
vjrantal is correct.  we need to make sure we have default settings for any of the values.  start_url can always be the URL, short_name can be the same as the name we makeup for the folder name.  I think we cover defaults for all the others.

**Comment by f2bo** [comment]
Fixed by using the target site's URL as the start_url (see https://github.com/manifoldjs/ManifoldJS/pull/82)
