### ISSUE TITLE
app fails to run on win10 if has space in short name

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#76]
It seems to fail because it sues the short name for the ID which can not have a space or foreign characters.  We should parse this value and take out anything incompatible. 

you can use site: http://merrypixmas.com/ as an example.

**Comment by f2bo** [comment]
Added code to sanitize the name. This is shared by other platforms (see https://github.com/manifoldjs/ManifoldJS/commit/47f46d0d03838e58497153cd349ceb18118ebe9f).

**Comment by f2bo** [comment]
Sanitization function needs to be updated to only allow the following:
([A-Za-z][A-Za-z0-9]*)(\.[A-Za-z][A-Za-z0-9]*)*
