### ISSUE TITLE
0.3 breaks whitelist with url+port #

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#90]
With the CLI, when I generate a package pointing to a URL with a port number like http://www.shiftrconnect.com:3000, the package breaks in Win10, the whitelist (ACUR) breaks in the generated XML manifest

**Comment by msrodri** [comment]
We couldn't reproduce the issue with a manifest pointing to http://www.shiftrconnect.com:3000 (it generates a valid ACUR rule).

However, we suspect that the issue might be related to the value used in the scope member. given the following manifest.json:

```
{
  "start_url": "http://www.shiftrconnect.com:3000",
  "scope": "http://*.shiftrconnect.com:3000"
}
```

The following invalid rule is generated in the XML manifest:

```
<uap:Rule Type="include" Match="http://:3000/*.shiftrconnect.com" />
```

We provided a fix for this (see https://github.com/manifoldjs/ManifoldJS/commit/2bef12a53a3f160ca1411dc328ffcc941c386f14). With this fix, the following rule is generated:

```
<uap:Rule Type="include" Match="http://*.shiftrconnect.com:3000" />
```
