### ISSUE TITLE
Include troubleshooting info in the generated app package

### ISSUE THREAD

**Issue by f2bo** [manifoldjs/ManifoldJS#96]
For example, the version of ManifoldJS that was used to generate the package.

**Comment by boyofgreen** [comment]
Also, we can use this identifier to see that a Windows 10 app has been generated with Manifoldjs

**Comment by msrodri** [comment]
Hi @boyofgreen,

Any suggestion about where to add this identifier in the Windows 10  app? I remember that we talked about some sort of custom XML element in the appxmanifest file (e.g. something like `<generationTool name="ManifoldJS" version="0.3.1" />`), but it seems that the app fails installing if there are XML elements not defined in the manifest schema. I've been looking at the [Package manifest schema reference for Windows 10 Insider Preview](https://msdn.microsoft.com/en-us/library/windows/apps/dn934820.aspx), but I couldn't find a suitable element for this.

Another alternative would be to add generation details as comments (see below) but I'm wondering if that will serve the purposes to identify the generated app:

```
<?xml version="1.0" encoding="utf-8"?> 

<!--Generation Tool: ManifoldJS (version 0.3.1)-->

<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
IgnorableNamespaces="uap mp"> 
...
```

**Comment by boyofgreen** [comment]
We played with a few options with the windows team and it seems like the comment is the only thing that will not fail.   I'll try to reach out to the VS team to see if they have any ideas.

**Comment by msrodri** [comment]
A *generationInfo.json* file is now included in the platform folders with the version of manifoldjs used to create the package.

In the case of windows 10 hosted apps, a comment is added to the manifest file to indicate the manifoldjs version. We opened a new issue (#119) to continue looking for better alternatives.
